make: Human.class student/Student.class teacher/Teacher.class Lab01.class
      
Lab01.class: Lab01.java
	javac Lab01.java
	     
teacher/Teacher.class: teacher/Teacher.java
	javac teacher/Teacher.java

student/Student.class: student/Student.java
	javac student/Student.java
		       
Human.class: Human.java
	javac Human.java

clean:
	rm -f Lab01.class
	rm -f teacher/Teacher.class
	rm -f student/Student.class
	rm -f Human.class
    
